### ISSUE TITLE
for GitdenReader

### ISSUE THREAD

**Issue by teytag** [FriendsOfEpub/WillThatBeOverriden#1]
Hi @JayPanoz 
If you have information about the basic CSS documentation of the "GitdenReader" RS application, can you share it? IOS and Android...

**Comment by JayPanoz** [comment]
Nope, don’t have any info about GitdenReader. 

To put it simply, it seems they’re not relying on `.css` or `.js` files to manage overrides/settings since I haven't found any in the `.ipa` package (which is just a zip by the way). Even checked the `.bundle`s

To sum up, they’re doing it in a way which you can’t access easily.

**Comment by teytag** [comment]
Thank you for info :)

N. Erhan Uzumcu
Art Director and EPUB Developer
W3C EPUB Community Group Member
TEYTAG Founder
(Turkish Electronic Publishing Desing and Research Group - Istanbul, Turkey)
https://independent.academia.edu/NErhanÜzümcü
http://teytagblog.blogspot.com.tr
http://www.teyid.org/ePub3Lib/
@ePub3Lib #teytag
